# -*- coding: utf-8 -*-
"""LVADSUSR113-selva-FINAL

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17q_5-MTgwSIFhdFpbFs-uAbBiPEWWCdi
"""

#1
import pandas as pd

walmart_data = pd.read_excel('/content/Walmart_Dataset Python_Final_Assessment.xlsx',sheet_name=0)

walmart_data.info()
walmart_data.describe()

#2
walmart_data.isnull().sum()
# The Dataset has 0 missing values
walmart_data.info()
print('The DataTypes are appropriate to the Data and does not have any Missing values')

#3
class Descriptive_statistics:
  def __init__(self,df):
    self.df = df
  def desc_sales(self):
    print('Descriptive statistics: ')
    avg_sales = self.df['Sales'].mean()
    print('\nAverage of Sales: ',avg_sales)
    mode_sales = self.df['Sales'].mode()
    print('Mode of Sales: ',mode_sales)
    median_sales = self.df['Sales'].median()
    print('Median of Sales: ',median_sales)
    minimum = self.df['Sales'].min()
    maximum = self.df['Sales'].max()
    print('The Range is between: ',minimum,' and',maximum)

  def desc_quantity(self):
    avg_quantity = self.df['Quantity'].mean()
    print('\n\nAverage of Quantity: ',avg_quantity)
    mode_quantity = self.df['Quantity'].mode()
    print('Mode of Quantity: ',mode_quantity)
    median_quantity = self.df['Quantity'].median()
    print('Median of Quantity: ',median_quantity)
    minimum = self.df['Quantity'].min()
    maximum = self.df['Quantity'].max()
    print('The Range is between: ',minimum,' and',maximum)

desc_stats_object = Descriptive_statistics(walmart_data)
desc_stats_object.desc_sales()
desc_stats_object.desc_quantity()

#4
import matplotlib.pyplot as plt
import seaborn as sns

class sales_visuals:
  def __init__(self,df):
    self.df = df
  def sales_by_Category(self):
    group_category = self.df.groupby(['Category']).agg({'Sales':'sum'})
    plt.figure(figsize=(8,6))
    plt.pie(group_category['Sales'],labels=self.df['Category'].unique())
    plt.show()
  def sales_distribution(self):
    sales = self.df[self.df['Sales']<200]
    sns.displot(sales['Sales'],kde=True)
    plt.title('Sales below $200')
    plt.show()
    sns.displot(self.df['Sales'],kde=True)
    plt.show()
v_obj = sales_visuals(walmart_data)
v_obj.sales_by_Category()
v_obj.sales_distribution()



#5
plt.bar(walmart_data['Quantity'],walmart_data['Sales'])
plt.show()
plt.bar(walmart_data['Profit'],walmart_data['Sales'])
plt.show()
plt.bar(walmart_data['Profit'],walmart_data['Quantity'])
plt.show()

#6
plt.boxplot(walmart_data['Sales'])
plt.show()
plt.boxplot(walmart_data['Quantity'])
plt.show()
plt.boxplot(walmart_data['Profit'])

"""
## There are outliers in the Sales column with values lying between 4000 and 14000
## -----------------------------------
# There are outliers in the Quantity column with values lying above 10

# There are outliers in the Profit column with values lying above 3000

"""

#7
# Trend analysis
# i)
from datetime import datetime
sns.lineplot(walmart_data['Sales'][:300])
sns.lineplot(walmart_data['Profit'][:300])
plt.legend()
plt.show()

#ii)
group_category = walmart_data.groupby(['Category']).agg({'Sales':'sum'})
plt.figure(figsize=(8,6))
plt.pie(group_category['Sales'],labels=walmart_data['Category'].unique())
plt.show()

"""# The Categories like Appliances, Machines, Copiers and Envelopes have shown a Significant Growth over all these years"""

# Customer Analytics
#i)
cust_group = walmart_data.groupby(['EmailID']).agg({'Sales':'sum','Order ID':'count'})
print('customer with most sales and order count: ')
print(cust_group[cust_group['Sales']==cust_group['Sales'].max()])

"""# customer with most sales and order count:
                           Sales  Order ID
EmailID                                   
RaymondBuch@gmail.com  14345.276         6
"""

# ii)
cust_group = walmart_data.groupby(['EmailID']).agg({'Sales':'sum','Order ID':'count'})
print('Buying behaviour:')
print(cust_group['Sales'])

# Comprehensive analysis
# i) Foucssing On More regions as the Sales is dense on only the major 4 cities
# ii) The Sales was focused on NEARBY cities and will be great to supply over some more regions in the United states.
# iii) High Value Customers have bought products with price Lower than $500 with quantity of more than 2, these customers did not place high number of orders.
#      To gain customer loyalty, the company should focus on products with price less than 500$ which are also bought multiple times

"""# Comprehensive analysis
# i) Foucssing On More regions as the Sales is dense on only the major 4 cities
# ii) The Sales was focused on NEARBY cities and will be great to supply over some more regions in the United states.
# iii) High Value Customers have bought products with price Lower than $500 with quantity of more than 2, these customers did not place high number of orders.
#      To gain customer loyalty, the company should focus on products with price less than 500$ which are also bought multiple times
"""