# -*- coding: utf-8 -*-
"""Python_Internal_Assessment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15oRKfYNx1hJTSoKX6WmM_Qwwdnj1AJsn
"""

# 1
print('To Calculate Area of a rectangle')
vAR_H = float(input('Input the Height: '))
vAR_W = float(input('Input the Width: '))
vAR_Area = vAR_H*vAR_W
print(f'Area of the rectangle is: {vAR_Area} unit square')

# 2
print('To Calculate The BMI')
var_H = float(input('Input the Height in metres: '))
var_W = float(input('Input the Weight: '))
var_BMI = var_W/(var_H**2)
print(f'Your BMI is: {var_BMI}')

# 3
students = {}
i='add'
while i == 'add':
  sName = input('Input the name of the student: ')
  sScore = input('Input the Score of the student: ')
  students[sName] = sScore
  i = input('type "add" for adding another student/ anything else to print the result: ').lower()
  if i!='add':
    print(students)

# 4
user_age = int(input('Enter your age: '))
if user_age<18:
  print('You are a Minor')
elif user_age<60:
  print('You are an Adult')
else:
  print('You are an Senior')

# 5
var_range =50
for i in range(1,var_range):
  if i%2==0:
    print(i," ")

# 6
user_password = {'admin':'abcd1234'}

while True:
  input_pass = input('Enter the correct password for admin: ')
  if user_password['admin'] == input_pass:
    print("Correct Password")
    break
  else:
    print("INCORRECT Password")

# 7
list_nums = input('Enter the list of numbers separated by a Comma: ').split(',')
total=0
for i in list_nums:
  total+=int(i)

average_nums = round(total/len(list_nums),2)
print(f'Average is: {average_nums}')

# 8
vowels = "aeiou"
input_string = input("Enter the string to calculate number of vowels: ")
count = 0
for i in input_string:
  if i in vowels:
    count+=1

print(f'The number of vowels is: {count}')

# 9
import datetime as dt

print(dt.datetime(year=2024,month=3,day=14,hour=16))

# 10
try:
  input_num = int(input('Enter a value: '))
except ValueError as e:
  print('You entered a non-numeric value')

# 11
try:
  input_num = int(input('Enter a Value that is not an integer: '))
except ValueError as e:
  print('Your input is not an integer Error:',e)

# 12
try:
  input_n = int(input('enter numerator: '))
  input_d = int(input('enter denominator (try zero): '))
  division = input_n/input_d
  print(division)
except ZeroDivisionError as e:
  print('The Denominator cannot be zero')

# 13
f = open('sample.txt','w')
f.writelines("Hello, Python!")
f.close()

# 14
f = open('sample.txt','r')
print(f.readline())
f.close()

# 15
f = open('sample.txt','r')
l = f.readlines()
l.append("New line")
f.close()
f = open('sample.txt','w')
f.writelines(l)